name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4
      
    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Installer les dépendances
      run: |
        pip install PyQt5 pyinstaller
        
    - name: Télécharger et préparer scrcpy Windows
      run: |
        Invoke-WebRequest -Uri "https://github.com/Genymobile/scrcpy/releases/download/v2.4/scrcpy-win64-v2.4.zip" -OutFile "scrcpy.zip"
        mkdir scrcpy-windows
        Expand-Archive -Path "scrcpy.zip" -DestinationPath "temp_extract" -Force
        Move-Item -Path "temp_extract/scrcpy-win64-v2.4/*" -Destination "scrcpy-windows/" -Force
        
    - name: Fabriquer le .exe
      run: |
                pyinstaller --onefile --windowed --icon=icon.ico --name "ScreenMirror" --add-data "scrcpy-windows/*;scrcpy-windows" main.py
        
    - name: Sauvegarder le résultat
      uses: actions/upload-artifact@v4
      with:
        name: MonAppMiroir-EXE
        path: dist/MonAppMiroir.exe
